### ISSUE TITLE
Installation error using Docker on Windows: #0 5.123 error: typing-extensions 4.5.0 is installed but typing-extensions>=4.6.1 is required by {'pydantic'}

### ISSUE THREAD

**Issue by J4k3j4k3** [techfreaque/octane#1]
Hi,

Just receiving the above error when trying to Docker installation on Windows during the initial build of the Docker image.

**Comment by J4k3j4k3** [comment]
As a temporary fix, adding typing-extensions>4.6.1 above requests==2.25.1
 in octobot-packages/Octobot/setup.py fixed it for me

**Comment by techfreaque** [comment]
Hey there, sorry for my late reply, didn't notice it.
Thanks a lot for the feedback, I already fixed it couple of weeks ago.
